export const STUDENTS_LIST_REQUEST = 'STUDENTS_LIST_REQUEST';
export const STUDENTS_LIST_SUCCESS = 'STUDENTS_LIST_SUCCESS';
export const STUDENTS_LIST_FAIL = 'STUDENTS_LIST_FAIL';

export const STUDENTS_DETAIL_REQUEST = 'STUDENTS_DETAIL_REQUEST';
export const STUDENTS_DETAIL_SUCCESS = 'STUDENTS_DETAIL_SUCCESS';
export const STUDENTS_DETAIL_FAIL = 'STUDENTS_DETAIL_FAIL';



export const STUDENT_UPDATE_REQUEST = 'STUDENT_UPDATE_REQUEST';
export const STUDENT_UPDATE_SUCCESS = 'STUDENT_UPDATE_SUCCESS';
export const STUDENT_UPDATE_FAIL = 'STUDENT_UPDATE_FAIL';
